### ISSUE TITLE
Request for Stegformer Model Checkpoint

### ISSUE THREAD

**Issue by longxiang-ai** [aoli-gei/StegFormer#1]
Hello @aoli-gei,

Thank you for your excellent work on Stegformer. I've been following the development and found your project incredibly useful.

I am currently exploring your code and am interested in testing the model further. Could you possibly share the **pre-trained checkpoints** of Stegformer? Access to these would significantly aid in my ongoing projects.

I understand that this might involve additional preparations on your part. Please let me know if there are specific conditions for using the checkpoints.

Thank you for considering my request. I look forward to your response and continue to admire your work.

Best regards,
longxiang-ai

**Comment by aoli-gei** [comment]
Hello Mingwei!
Thank you for your interest, here you are: [model](https://drive.google.com/drive/folders/1L__astCCgm2GlQU-YaxZYTIzEnABdKEc?usp=sharing)
