### ISSUE TITLE
测试显存占用超过24GB？

### ISSUE THREAD

**Issue by ClintWestwo0d** [aoli-gei/StegFormer#4]
作者你好！我在指定一张显存24GB的显卡运行测试脚本 test_save_single_image_hiding.py  [https://github.com/aoli-gei/StegFormer/blob/master/test_save_single_image_hiding.py](url)，报错CUDA out of memory。

请问测试显存需要占用多大显存？感谢回复！

**Comment by ClintWestwo0d** [comment]
Sorry that was a foolish mistake！！

**Comment by aoli-gei** [comment]
> Sorry that was a foolish mistake！！

lol, Just a slight problem~ Blondie
